# Generated by Django 2.1.5 on 2022-03-15 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artheme',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False, verbose_name='theme id')),
                ('at_name', models.CharField(max_length=50, verbose_name='theme name')),
                ('at_count', models.IntegerField(default=0, verbose_name='have how many articles')),
                ('at_cover', models.ImageField(upload_to='upload/theme/', verbose_name='theme cover picture')),
                ('at_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='belong to which user')),
                ('authors', models.ManyToManyField(related_name='article_theme', to=settings.AUTH_USER_MODEL, verbose_name='which user subscribed')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, verbose_name='article id')),
                ('article_content', models.TextField(verbose_name='publish content')),
                ('publish_time', models.DateField(auto_now_add=True, verbose_name='publish time')),
                ('article_title', models.CharField(max_length=200, verbose_name='article title')),
                ('article_img', models.ImageField(default='/media/upload/ar/moren.jpg', upload_to='upload/ar/', verbose_name='article cover image')),
                ('count_all_liked', models.IntegerField(default=0, verbose_name='how many person liked')),
                ('count_all_collected', models.IntegerField(default=0, verbose_name='how many person collected')),
                ('count_all_commented', models.IntegerField(default=0, verbose_name='how many person commented')),
                ('count_all_words', models.IntegerField(default=0, verbose_name='count article words')),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='belong to which user')),
                ('article_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Artheme', verbose_name='belong to which theme')),
                ('which_authors_collected', models.ManyToManyField(related_name='articles_collected', to=settings.AUTH_USER_MODEL, verbose_name='which user collected')),
                ('which_authors_liked', models.ManyToManyField(related_name='articles_liked', to=settings.AUTH_USER_MODEL, verbose_name='which user liked')),
            ],
        ),
    ]
